# name: my_new_app
# description: A new Flutter project.

# version: 1.0.0+1

# environment:
#   sdk: ">=2.17.0 <3.0.0"

# dependencies:
#   flutter:
#     sdk: flutter

#   # Add the cupertino_icons package here
#   cupertino_icons: ^1.0.6

#   # Other dependencies
#   firebase_core: ^2.8.0
#   firebase_storage: ^11.0.0
#   image_picker: ^0.8.6

# dev_dependencies:
#   flutter_test:
#     sdk: flutter

# # For information on the generic Dart part of this file, see the
# # following page: https://dart.dev/tools/pub/pubspec
# # The following section is specific to Flutter.
# flutter:

#   # The following line ensures that the Material Icons font is
#   # included with your application, so that you can use the icons in
#   # the material Icons class.
#   uses-material-design: true

#   # To add assets to your application, add an assets section, like this:
  
    
    
#   # An image asset can refer to one or more resolution-specific "variants", see
#   # https://flutter.dev/assets-and-images/#resolution-aware.
#   # For details regar
    # ding adding assets from package dependencies, see
#   # https://flutter.dev/assets-and-images/#from-packages

#   # To add custom fonts to your application, add a fonts section here,
#   # in this "flutter" section. Each entry in this list should have a
#   # "family" key with the font family name, and a "fonts" key with a
#   # list giving the asset and other descriptors for the font. For
#   # example:
#   # fonts:
#   #   - family: Schyler
#   #     fonts:
#   #       - asset: fonts/Schyler-Regular.ttf
#   #       - asset: fonts/Schyler-Italic.ttf
#   #         style: italic
#   #   - family: Trajan Pro
#   #     fonts:
#   #       - asset: fonts/TrajanPro.ttf
#   #       - asset: fonts/TrajanPro_Bold.ttf
#   #         weight: 700
#   #
#   # For details regarding fonts from package dependencies,
#   # see https://flutter.dev/custom-fonts/#from-packages


name: color_detector_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.0
  firebase_core: ^2.4.0
  # firebase_auth: ^4.7.2
  firebase_analytics: ^10.1.0
  firebase_storage: ^11.0.0
  image: ^3.2.0
  image_picker: ^0.8.5+3
  google_mlkit_face_detection: ^0.5.0  # ?this is my reak facedetecr

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/1.jpg
    - images/2.png
    - images/girl1.jpg
    - images/logo.png
    - images/logo1.png
    - images/b1.png
    - images/b2.png
    - images/b3.png
    - images/b4.png
    - images/b5.png
    - images/b6.png
    - images/b7.png
    - images/b8.png
    - images/b9.png